apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-runrun-backend
  labels:
    app: mini-runrun-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mini-runrun-backend
  template:
    metadata:
      labels:
        app: mini-runrun-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/Sandeepsardesi/mini-runrun-backend:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
